- hosts: DNS
  become: "{{ sudo | default('yes') }}"
  roles:
    - common
    - bind
    - database
    - apache2
    - namedmanager
  vars:
    # common
    common_ipv4_forward: 1
    common_ssh_port: 2400
    # variabili per ruolo common
    users:
      - name: michele
        authorized:
          - ./keys/michele.pub
    # bind
    tld: 'nnxx'
    hostmaster: 'admin.basilicata.nnxx'
    nameservers_hosts:
       ns1:
         ip: '10.20.30.40'
    # namedmanager
    db_host: "localhost"
    db_name: "namedmanager"
    db_user: "namedmanager"
    db_pass: "ninux"
    api_url: "http://10.20.30.40/namedmanager"
    api_server_name: "dns.nnxx"
    api_auth_key: "ninux"


