---
- name: 1. install Apache
  apt: name=apache2 state=present
- name: 2. install PHP module for Apache
  apt: name=libapache2-mod-php5 state=present
- name: 3. start Apache
  service: name=apache2 state=running enabled=yes
- name: 4. create index.php with phpinfo
  copy: src=index.php dest=/var/www/html/index.php mode=0664
- name: 5. remove default index.html
  file:
    path: /var/www/html/index.html
    state: absent

- block:
  - name: install apache components
    apt: "pkg={{ item }} state=latest"
    with_items:

      - apache2.2-common
      - apache2-doc
      - apache2-mpm-prefork
      - apache2-utils
      - libexpat1
      - ssl-cert
      - libapache2-mod-php5
      - libapache2-mod-fcgid
      - apache2-suexec
      - mcrypt
      - imagemagick
      - libruby
      - libapache2-mod-python
      - memcached
      - libapache2-mod-passenger
  tags:
    - apache2

- block:
  - name: install php components
    apt: "pkg={{ item }} state=latest"
    with_items:

      - php5-common
      - php5-gd
      - php5-apcu
      - php5-fpm
      - php5-mysql
      - php5-curl
      - php5-gd
      - php5-intl
      - php-pear
      - php5-imagick
      - php5-imap
      - php5-mcrypt
      - php5-memcache
      - php5-memcached
      - php5-pspell
      - php5-recode
      - php5-sqlite
      - php5-tidy
      - php5-xmlrpc
      - php5-xsl
      - php5-geoip
      - memcached
      - php5-cli
      - php5-cgi
      - php-auth
      - php5-mcrypt
      - php5-pspell
  tags:
    - php

- name: enabled rewrite
  apache2_module: name=rewrite state=present
- name: enabled suexec
  apache2_module: name=suexec state=present
- name: enabled suexec
  apache2_module: name=suexec state=present
- name: enabled ssl
  apache2_module: name=ssl state=present
- name: enabled actions
  apache2_module: name=actions state=present
- name: enabled include
  apache2_module: name=include state=present
- name: enabled auth_digest
  apache2_module: name=auth_digest state=present
- name: enabled cgi
  apache2_module: name=cgi state=present

- name: Install PHPMyAdmin
  apt: pkg=phpmyadmin state=installed

- file:
    src: /etc/phpmyadmin/apache.conf
    dest: /etc/apache2/conf-enabled/phpmyadmin.conf
    state: link
  notify: restart apache2
