---
- name: 1. install Apache
  apt: name=apache2 state=present
- name: 2. install PHP module for Apache
  apt: name=libapache2-mod-php7.0 state=present
- name: 3. start Apache
  service: name=apache2 state=started enabled=yes
- name: 4. create index.php with phpinfo
  copy: src=index.php dest=/var/www/html/index.php mode=0664
- name: 5. remove default index.html
  file:
    path: /var/www/html/index.html
    state: absent

- block:
  - name: install apache components
    apt: "pkg={{ item }} state=latest"
    with_items:
      - apache2
      - apache2-doc
      - apache2-utils
      - libapache2-mod-php
      - libapache2-mod-fcgid
      - apache2-suexec-pristine
      - libapache2-mod-python
      - libapache2-mod-passenger
      - libexpat1
      - ssl-cert
      - libapache2-mod-php7.0
      - mcrypt
      - imagemagick
      - libruby
      - memcached
      - certbot
  tags:
    - apache2

- block:
  - name: install php components
    apt: "pkg={{ item }} state=latest"
    with_items:
      - php7.0
      - php7.0-common
      - php7.0-gd
      - php7.0-mysql
      - php7.0-imap
      - php7.0-cli
      - php7.0-cgi
      - php-pear
      - php7.0-mcrypt
      - php7.0-curl
      - php7.0-intl
      - php7.0-pspell
      - php7.0-recode
      - php7.0-sqlite3
      - php7.0-tidy
      - php7.0-xmlrpc
      - php7.0-xsl
      - php-memcache
      - php-imagick
      - php-gettext
      - php7.0-zip
      - php7.0-mbstring
      - php7.0-soap
  tags:
    - php

- name: enabled rewrite
  apache2_module: name=rewrite state=present
- name: enabled suexec
  apache2_module: name=suexec state=present
- name: enabled suexec
  apache2_module: name=suexec state=present
- name: enabled ssl
  apache2_module: name=ssl state=present
- name: enabled actions
  apache2_module: name=actions state=present
- name: enabled include
  apache2_module: name=include state=present
- name: enabled auth_digest
  apache2_module: name=auth_digest state=present
- name: enabled cgi
  apache2_module: name=cgi state=present

- name: Install PHPMyAdmin
  apt: pkg=phpmyadmin state=installed

- file:
    src: /etc/phpmyadmin/apache.conf
    dest: /etc/apache2/conf-enabled/phpmyadmin.conf
    state: link
  notify: restart apache2
