---
# defaults variables for bind
tld: 'nnxx'
hostmaster: 'admin.nnxx'
#reverse_zone: 'db.10.27'
#reverse_arpa: '27.10.in-addr.arpa'

nameservers_hosts:
  ns1:
    ip: '10.27.0.120'



# {{ ansible_default_ipv4.address }}
