---
- block:
  - name: #1. install bind packages
    apt: "pkg=bind9 state=latest"
  tags:
    - bind

- name: #2. create zone reverse /16
  template:
    src: db.rev.j2
    dest: /etc/bind/{{ reverse_zone }}
    owner: root
    group: bind
    mode: 0664

- name: #3. create zone TLD nnxx
  template:
    src: db.zone.j2
    dest: /etc/bind/db.nnxx
    owner: root
    group: bind
    mode: 0664

- name: #4. create default zone
  template:
    src: named.conf.default-zones.j2
    dest: /etc/bind/named.conf.default-zones
    owner: root
    group: bind
    mode: 0664

- name: #5. copy named options
  copy:
    src: ../files/named.conf.options
    dest: /etc/bind/named.conf.options
